<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <RootNamespace>ParallelSeat.Overlay</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ParallelSeat.Core\ParallelSeat.Core.csproj" />
    <ProjectReference Include="..\ParallelSeat.Windows\ParallelSeat.Windows.csproj" />
  </ItemGroup>
</Project>
