<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ParallelSeat.Ipc</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ParallelSeat.Protocol\ParallelSeat.Protocol.csproj" />
    <PackageReference Include="System.IO.Pipes.AccessControl" Version="5.0.0" />
  </ItemGroup>
</Project>
